# Generated by Django 4.1.7 on 2023-02-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
