# Generated by Django 4.1.7 on 2023-02-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploads', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='age',
        ),
    ]
